//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopping.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to include customer.
        /// </summary>
        public static string CustFailAdd {
            get {
                return ResourceManager.GetString("CustFailAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure to update customer profile.
        /// </summary>
        public static string CustFailUpdate {
            get {
                return ResourceManager.GetString("CustFailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail not informed or not valid.
        /// </summary>
        public static string CustNotEmail {
            get {
                return ResourceManager.GetString("CustNotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        public static string CustNotFound {
            get {
                return ResourceManager.GetString("CustNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not informed.
        /// </summary>
        public static string CustNotInf {
            get {
                return ResourceManager.GetString("CustNotInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not informed.
        /// </summary>
        public static string CustNotName {
            get {
                return ResourceManager.GetString("CustNotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Customer.
        /// </summary>
        public static string CustomerAdd {
            get {
                return ResourceManager.GetString("CustomerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate not valid.
        /// </summary>
        public static string CustomerBirthdate {
            get {
                return ResourceManager.GetString("CustomerBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer.
        /// </summary>
        public static string CustomerUpdate {
            get {
                return ResourceManager.GetString("CustomerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem.
        /// </summary>
        public static string GerException {
            get {
                return ResourceManager.GetString("GerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string GerNotFound {
            get {
                return ResourceManager.GetString("GerNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ôps! Crach!!.
        /// </summary>
        public static string GerOps {
            get {
                return ResourceManager.GetString("GerOps", resourceCulture);
            }
        }
    }
}
